import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ReactNode } from "react";
import { Providers } from "@/app/[locale]/providers";
import "./globals.css";
import { auth } from "@/auth";
import { Navbar } from "@/lib/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "pl" }, { locale: "ru" }];
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: ReactNode;
  params: {
    locale: string;
  };
}) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className="kinguru">
        <Providers params={{ locale, messages }}>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
